# Generated by Django 4.1.1 on 2022-11-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static\\images\x07vatar.svg', null=True, upload_to=''),
        ),
    ]
